[package]
name = "rsbinder-tests"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1"
rsbinder = { version = "0.1.0", path = "../rsbinder" }
rsbinder-hub = { version = "0.1.0", path = "../rsbinder-hub" }
tokio = { version = "1", features = ["full"] }
env_logger = "0"
nix = "0"

[build-dependencies]
rsbinder-aidl = { version = "0.1.0", path = "../rsbinder-aidl" }
