[package]
name = "rsbinder-tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsbinder = { path = "../rsbinder" }
rsbinder-hub = { path = "../rsbinder-hub" }
env_logger = "0"
tokio = { version = "1", features = ["full"] }
nix = { version = "0", features = ["mount"] }
log = "0.4"
