[package]
name = "rsbinder-tools"
version = "0.2.0"
edition = "2021"
license = "Apache-2.0"
description = "This provides a few CLI binder tools for Linux."
homepage = "https://github.com/hiking90/rsbinder"
repository = "https://github.com/hiking90/rsbinder/rsbinder-tools"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1"
rsbinder = { version = "0.2.0", path = "../rsbinder" }
rsbinder-hub = { version = "0.2.0", path = "../rsbinder-hub" }
log = "0.4"
env_logger = "0.11"
nix = "0"
anstyle = "1.0"
