[package]
name = "rsbinder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1"
libc = { version = "0.2", default-features = false }
nix = "0"
log = "0.4"
pretty_hex = { version = "0", package = "pretty-hex" }
downcast-rs = "1.2"

[build-dependencies]
rsbinder-aidl = { path = "../rsbinder-aidl" }
