[package]
name = "rsbinder"
version = "0.1.2"
edition = "2021"
license = "Apache-2.0"
description = "This is a library for Linux Binder communication."
homepage = "https://github.com/hiking90/rsbinder"
repository = "https://github.com/hiking90/rsbinder"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = { version = "0", features = ["ioctl", "mount", "fs", "feature", "mman", "process"] }
log = "0.4"
pretty_hex = { version = "0", package = "pretty-hex" }
downcast-rs = "1.2"
