[package]
name = "rsbinder"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
description = "This is a library for Linux Binder communication."
homepage = { workspace = true }
repository = { workspace = true }
readme = "README.md"
rust-version = { workspace = true }
keywords.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["tokio"]
sync = ["rsbinder-aidl/sync"]
tokio = ["async", "tokio/full"]
async = ["rsbinder-aidl/async", "async-trait"]

[dependencies]
rustix = { workspace = true, features = ["process", "param", "mm"] }
log = { workspace = true }
pretty_hex = { workspace = true }
downcast-rs = { workspace = true }
async-trait = { workspace = true, optional = true }
lazy_static = { workspace = true }
tokio = { workspace = true, optional = true }

[build-dependencies]
rsbinder-aidl = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }
