[package]
name = "example-hello"
version = "0.1.2"
publish = false
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1"
rsbinder = { version = "0.1.2", path = "../rsbinder" }
rsbinder-hub = { version = "0.1.2", path = "../rsbinder-hub" }
env_logger = "0"
backtrace = "0.3"

[build-dependencies]
rsbinder-aidl = { version = "0.1.2", path = "../rsbinder-aidl" }
