[package]
name = "example-hello"
version = "0.2.0"
publish = false
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1"
rsbinder = { version = "0.2.0", path = "../rsbinder" }
rsbinder-hub = { version = "0.2.0", path = "../rsbinder-hub" }
env_logger = "0.11"
async-trait = "0.1"

[build-dependencies]
rsbinder-aidl = { version = "0.2.0", path = "../rsbinder-aidl" }
