name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  rust_min: '1.71'

jobs:
  android-build:
    name: android-build
    runs-on: ubuntu-latest
    needs:
      - linux-build

    steps:
    - uses: actions/checkout@v4
    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r26c
        add-to-path: false
        local-cache: true
    - name: Install ndk targets
      run: rustup target add x86_64-linux-android
    - name: Install cargo-ndk
      run: cargo install cargo-ndk
    - name: Build for Android
      run: cargo ndk -t x86_64-linux-android build

  linux-build:
    name: linux-build
    runs-on: ubuntu-latest
    needs:
      - binder-prepare
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust ${{ env.rust_min }}
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.rust_min }}
      - uses: Swatinem/rust-cache@v2
      - name: "check --workspace --all-features"
        run: cargo check --workspace --all-features
        env:
          RUSTFLAGS: "" # remove -Dwarnings

  binder-prepare:
    name: binder-prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Anbox Modules
        uses: actions/checkout@v2
        with:
          repository: choff/anbox-modules
          ref: master 
  
      - name: Install DKMS
        run: sudo apt-get update && sudo apt-get install -y dkms
  
      - name: Run install.sh from Anbox Modules
        run: |
          chmod +x INSTALL.sh
          ./INSTALL.sh
