name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r26c
        add-to-path: false
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        targets: aarch64-linux-android, armv7-linux-androideabi
    - name: Install ndk targets
      run: rustup target add x86_64-linux-android
    - name: Build for Linux
      run: cargo build --verbose
    - name: Build for Android
      run: cargo ndk -t x86_64-linux-android build --verbose
    - name: Run tests
      run: cargo test --verbose
